config/routes.rb
Rails.application.routes.draw do
  root 'main#home'
  devise_for :users
  # get 'file_storages/index'
  # get 'file_storages/new'
  # get 'file_storages/create'
  # get 'file_storages/destroy'
  resources :file_storages, only: [:index, :new, :create, :destroy]  
  get 'file_storages/:id' => 'file_storages#download', as:'download_file_storage'
  get 'user/:id' => 'user#show', as:'user_show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # devise_scope :user do
  #   match '/sign-in' => "devise/sessions#new", :as => :login
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/file_storage.rb
class FileStorage < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader
    validates :name, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :file_storages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :name, :age]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def check_login_user!
    if !user_signed_in?
      redirect_to "/", :notice => 'User not logged in!'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end
end
   
  

app/controllers/file_storages_controller.rb
require 'rack/mime'
class FileStoragesController < ApplicationController
  before_action :check_login_user!
  def index
    if params[:name].present?
      @file_storages = FileStorage.where('name LIKE ?', "%#{params[:name]}%")
    else
      @file_storages = FileStorage.all
    end
  end

  def new
    @file_storage = FileStorage.new
  end

  def create
    @file_storage = FileStorage.new(file_storage_params)
    if @file_storage.save
      redirect_to file_storages_path, notice: 'Successfully uploaded.'
    else
      render :new
    end
  end

  def destroy
    @file_storage=FileStorage.find(params[:id])
    if current_user == @file_storage.user
      @file_storage.destroy
      redirect_to file_storages_path, notice: 'Successfully deleted.'
    else 
      redirect_to file_storages_path, notice: 'You are not the author. Please try again.'   
    end
  end
    

  def download
    @file_storage = FileStorage.find(params[:id])
    extension = Rack::Mime::MIME_TYPES.invert[@file_storage.attachment.content_type]
    send_file @file_storage.attachment.path, :type => @file_storage.attachment.content_type, :filename => @file_storage.name+"#{extension}", :disposition => 'attachment'
  end

  private   
  def file_storage_params   
    params.require(:file_storage).permit(:name, :attachment, :user_id)   
  end   
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :check_login_user!
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_storages_helper.rb
module FileStoragesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/file_storages/create.html.erb
<h1>FileStorages#create</h1>
<p>Find me in app/views/file_storages/create.html.erb</p>

app/views/file_storages/destroy.html.erb
<h1>FileStorages#destroy</h1>
<p>Find me in app/views/file_storages/destroy.html.erb</p>

app/views/file_storages/index.html.erb
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  
<br>   
  
<%= link_to "New File", new_file_storage_path, class: "btn btn-primary" %>   
<br>   
<br>   
  

<table class="table table-striped">   
   <thead>   
      <tr>   
         <th>#</th>
         <th>Candidate Name</th>   
         <th>View file</th>   
         <th>Download file</th>
         <th>Action</th>   
      </tr>   
   </thead>   
      
   <tbody>   
      <% @file_storages.each_with_index  do |file_storage, index| %>      

      <%= form_tag(books_path, method : get) do %>
         <%= text_field_tag :term %>
         <%= submit_tag 'Search' %>
      <% end %>

         <tr>   
            <td><p class="h4"><%= index %></p></td>
            <td><p class="h4"><%= file_storage.name %></p></td>   
            <td><%= link_to "View file", file_storage.attachment_url, class: "btn btn-info" %></td>   
            <td><%= link_to "Download file", download_file_storage_url(id: file_storage.id), class: "btn btn-success" %></td>   
            <td><%= button_to "Delete",  file_storage, :method => :delete, confirm: "Are you sure you want to delete #{file_storage.name}?", class: "btn btn-danger" %></td>   
         </tr>   
            
      <% end %>   
   </tbody>   
      
</table>   
</div>  

app/views/file_storages/new.html.erb
<div class="container bg-light w-25">   
   <% if !@file_storage.errors.empty? %>   
      <div>   
            
         <ul>   
            <% @file_storage.errors.full_messages.each do |msg| %>   
               <li style="color: red;"><%= msg %></li>   
            <% end %>      </ul>   
            
      </div>   
   <% end %>   

   
   <h2>New Book</h2>
   <%= form_for @file_storage, html: { multipart: true } do |f| %>   
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="form-group">
         <%= f.label :name %>   
         <%= f.text_field :name, class: "form-control" %>   
      </div>
      <div class="form-group">
         <%= f.label :attachment %>   
         <%= f.file_field :attachment, class: "form-control" %>  
      </div>
      <div class="form-group">
         <%= f.submit "Save", :class => " btn btn-primary" %>   
      </div>       
   <% end %>   

   <%= link_to "Turn back to book list", "/file_storages", :method => :get, class: "btn btn-secondary" %>
</div>  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">	
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#example-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Navbar</a>
		</div>		
		<div class="collapse navbar-collapse" id="example-1">
			<ul class="nav navbar-nav" style="display: flex; align-items: center; float: left;">
				<% if current_user %>
					<li class="nav-item"> <%= link_to "File Storage", file_storages_url %></li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav" style="display: flex; align-items: center; float: right;">
				<% if current_user %>
					<li class="nav-item"> <%= link_to "User Information", user_show_url(:id => current_user.id) %></li>
					<li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_url %></li>
					<li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %></li>
				<% else %>
					<li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path %></li>
					<li class="nav-item"> <%= link_to "Sign In", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>	
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag "application", "data-turbo-track" => true %> <%= javascript_importmap_tags
    %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container-fluid">
      <p class="notice" style="color: red; text-align:center;"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/home.html.erb
<h1 style="text-align: center;">Welcome to our Website</h1>

app/views/user/show.html.erb
<div class="container mx-auto" style="background-color: #D2C6C3; text-align: center; border-radius: 20px">
    <h1>User information</h1>
    <div class="card">
        <div class="row">
            <div class="col-md-6">
                <% if @user.name %>
                    <h3 class="card-title d-inline-block">Name: </h3>
                    <p class="card-text d-inline-block"><%= @user.name %></p> <br/>
                <% end %>
                <% if @user.age %>
                    <h3 class="card-title d-inline-block">Age: </h3>
                    <p class="card-text d-inline-block"><%= @user.age %></p> <br/>
                <% end %>
                <h2 class="card-title">Contact with me: </h2>
                <p class="card-text"><%= @user.email %></p>
            </div>
            <div class="col-md-6">
                <% if current_user.id == @user.id %>
                    <div style="margin-bottom: 5px;">
                        <%= button_to "Edit account", edit_user_registration_url, :method => :get, class: "btn btn-primary" %>
                    </div>
                <% end %>
                
                <div style="margin-bottom: 5px;">
                    <%= button_to "Back to list file", file_storages_url, :method => :get, class: "btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>
</div>